version: '2'
services:
  api-app:
    image: api
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://api-postgresql:5432/api
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://api-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://api-elasticsearch:9200
    ports:
      - 8080:8080
  api-postgresql:
    extends:
      file: postgresql.yml
      service: api-postgresql
  api-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: api-elasticsearch
